#!/usr/bin/env python3
"""Regenerate committed TypeScript definitions using Python only."""

import argparse
import json
from pathlib import Path

import council_protocol as protocol

EXPORTS = (
    "SCHEMA_VERSION", "DIALOGUE_SCHEMA_VERSION", "BROKER_VERSION",
    "ENVELOPE_PREAMBLE", "RELAY_ENVELOPE_KINDS", "ERROR_REASONS",
    "SUBMIT_KINDS", "REQUEST_SUBMISSION_KINDS", "CLAIM_IMPORTANCE_LEVELS",
    "CLAIM_POSITIONS", "CONCESSION_BASES", "SUBSTANTIVE_CONCESSION_BASES",
    "RESOLUTION_COSTS", "MAX_LINE_BYTES", "MAX_SUBMISSION_BYTES",
    "MAX_ENVELOPE_BYTES", "MAX_COUNCIL_ROUNDS", "MAX_COUNCIL_PARTICIPANTS",
    "MAX_ACTIVE_CLAIM_CEILING", "DEFAULT_ACTIVE_CLAIM_CEILING",
    "DEFAULT_MINIMUM_ROUNDS", "DEFAULT_ROUNDS", "DEFAULT_MAX_ROUNDS",
    "DEFAULT_LEASE_MINUTES", "MAX_LEASE_MINUTES", "MAX_WAIT_SECONDS", "FIELD_SCHEMAS",
)


def zod_field(field):
    """Compile the deliberately bounded static argument vocabulary, not validators."""
    if "enum" in field:
        result = "z.enum(" + json.dumps(field["enum"]) + ")"
    else:
        kind = field["type"]
        if kind == "string":
            result = "z.string()"
        elif kind == "integer":
            result = "z.number().int()"
        elif kind == "boolean":
            result = "z.boolean()"
        elif kind == "object":
            result = "z.record(z.string(), z.any())"
        elif kind == "array":
            item = zod_field(field["items"]) if field.get("items") else "z.any()"
            result = "z.array(" + item + ")"
        else:
            raise ValueError("unsupported OpenCode field type: %r" % kind)
    for source, method in (("minimum", "min"), ("maximum", "max"),
                           ("minItems", "min"), ("maxItems", "max")):
        if source in field:
            result += ".%s(%d)" % (method, field[source])
    # Omit schema defaults intentionally: inserting a default erases provenance.
    # Peer uniqueness/exclusivity and cross-field policy checks stay in the broker.
    return result


def render():
    lines = [
        "// Generated by scripts/generate_protocol.py. Edit council_protocol.py.",
        'import type { tool } from "@opencode-ai/plugin"',
        '',
        'export const PACKAGE_ID = "unstamped"',
        'export const RUNTIME_COHORT = "unstamped"',
        '',
    ]
    for name in EXPORTS:
        value = getattr(protocol, name)
        encoded = json.dumps(value, ensure_ascii=False, indent=2)
        suffix = " as const" if isinstance(value, (tuple, dict, list)) else ""
        lines.append("export const %s = %s%s" % (name, encoded, suffix))
    lines.extend(['', 'export function openCodeToolArgs(z: typeof tool.schema) {', '  return {'])
    for name in protocol.TOOL_SCHEMAS:
        if name in ("council_pending_wakes", "council_wake_ack"):
            continue
        schema = protocol.tool_schema(name, "opencode")
        lines.append("    %s: {" % name)
        for field, definition in schema["properties"].items():
            value = zod_field(definition)
            if field not in schema.get("required", []):
                value += ".optional()"
            lines.append("      %s: %s," % (field, value))
        lines.append("    },")
    lines.extend(['  }', '}', ''])
    return "\n".join(lines)


def normalized_stamps(text):
    import re
    return re.sub(r'(?m)^((?:(?:export )?const )?(?:PACKAGE_ID|RUNTIME_COHORT) = )"[^"]+"',
                  r'\1"unstamped"', text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).with_name("council_protocol.ts")
    expected = render()
    if args.check:
        if not path.is_file() or normalized_stamps(path.read_text()) != expected:
            parser.exit(1, "TypeScript protocol is stale; run python3 scripts/generate_protocol.py\n")
    else:
        path.write_text(expected)


if __name__ == "__main__":
    main()
